# parent image
FROM alpine:latest
# zainstaluj curl i nmap (apk add) RUN czy CMD?

# uwórz użytkownika baim i zmień się na niego

# przejdz do folderu jsons

# skopiuj wszystkie pliki


# na koniec
CMD ["tail", "-f", "/dev/null"]