# parent image
FROM alpine:latest

# uwórz użytkownika baim i zmień się na niego

# przejdz do folderu jsons

# skopiuj wszystkie pliki

# zainstaluj curl i nmap (apk add) RUN czy CMD?

# na koniec
CMD ["tail", "-f", "/dev/null"]